#!/bin/sh
#
# @name Gazebo x500 depth down
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default NAV_DLL_ACT 0
param set-default COM_RCL_EXCEPT 7
