<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>0.1.0</version>
  <description>Launch files and world configuration for the UAV-guided UGV system.</description>
  <maintainer email="jashan@todo.todo">jashan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ackermann_gz_bringup</exec_depend>
  <exec_depend>drdo_gz_worlds</exec_depend>
  <exec_depend>road_survey</exec_depend>
  <exec_depend>guidance</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
